apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: fts3-db
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-admin
    key: password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-user
    key: password

  image:
    repository: mariadb
    tag: "11.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: wekafs--sdf-k8s01
    accessModes:
      - ReadWriteOnce

  #https://github.com/mariadb-operator/mariadb-operator/issues/137#issuecomment-1585819345
  #tls:
  #  secretRef: # reference to an existing TLS secret
  #    name: tls
  #  certificateRef: # reference to a cert-manager Certificate resource
  #    name: cert
  #  selfSigned: true # the operator will generate a self-signed certificate
  #  autoReload: true # reload the StatefulSet whenever the certificate changes

  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  env:
    - name: TZ
      value: SYSTEM

  envFrom:
    - configMapRef:
        name: mariadb

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false
