namespace: fts3-db

resources:
  - ns.yaml
  - service.yaml
  - fts3-instance.yaml
  - fts3-database.yaml
  - fts3-grant.yaml

configMapGenerator:
  - name: mariadb-config
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []
  - name: mariadb-init
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []
  - name: mariadb-server
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals:
      - MARIADB_DATABASE=fts3
  - name: mariadb-metrics
    options:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    literals: []

secretGenerator:
  - name: mariadb-admin
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    files:
    - password=etc/.secrets/fts3db-root-password
  - name: mariadb-user
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/component: server
    files:
    - password=etc/.secrets/fts3db-fts3-password
    - username=etc/.secrets/fts3db-username

#images:
#  - name: mariadb-server
#    newName: library/mariadb
#    newTag: "10.11.2"
#  - name: mariadb-metrics
#    newName: prom/mysqld-exporter
#    newTag: "v0.14.0"
