apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-fts3
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        image: slaclab/grid-security-files:latest
        command: ["/bin/bash", "-c", "chmod 755 /out/ && cp -rv --preserve=links /grid-certificates/* /out/"]
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         emptyDir: {}
