apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdf-fts3
spec:
  template:
    spec:
      initContainers:
      - name: grid-certs
        #image: slaclab/grid-security-files:latest
        image: bjwhitefnal/grid-security-files:latest
        command: 
        - cp
        - -a 
        - /grid-certificates/.
        - /out/
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
      volumes:
       - name: ca-volume
         secret:
           $patch: delete
         emptyDir: {}
