apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: fts3
  namespace: fts3-db
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: mariadb-user
    key: password
  # This field is immutable and defaults to 10
  maxUserConnections: 20
